environment:
  APPVEYOR_SSH_BLOCK: true
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor.monacelli@streambox.com

image: Ubuntu2004
install:
- sudo apt -qqy update
- sudo apt -qy install python3.8-venv
- python3 -mvenv .venv
- source .venv/bin/activate
- pip install tox
- make install
test_script:
- source .venv/bin/activate && tox
build: off
